export const cpStats = [
  {
    platform: 'LeetCode',
    color: '#FFA116',
    bgColor: 'rgba(255, 161, 22, 0.1)',
    stat: '400+',
    numericStat: 400,
    statLabel: 'Problems Solved',
    badge: 'Consistent Solver',
    link: 'https://leetcode.com/Just_Ritik_Things/',
    visual: 'progress-ring',
    progress: 80,
  },
  {
    platform: 'CodeChef',
    color: '#5B4638',
    bgColor: 'rgba(91, 70, 56, 0.15)',
    stat: '1605',
    numericStat: 1605,
    statLabel: 'Rating',
    badge: '3★ Rated',
    extra: '★★★',
    link: 'https://www.codechef.com/users/hard_shore_99',
    visual: 'stars',
    progress: 60,
  },
  {
    platform: 'Codeforces',
    color: '#1F8ACB',
    bgColor: 'rgba(31, 138, 203, 0.1)',
    stat: '100+',
    numericStat: 100,
    statLabel: 'Problems Solved',
    badge: 'Active Contestant',
    link: 'https://codeforces.com/profile/Ritik-_-',
    visual: 'progress-ring',
    progress: 40,
  },
]
