export const projects = [
  {
    id: 1,
    title: 'CodeRax',
    tagline: 'Full-stack CP platform with AI battles',
    description:
      'A comprehensive competitive programming platform with a custom problem arena, real-time 1v1 DSA battles with ELO ranking, AI revision mentor (Groq), voice-driven mock interviews (Gemini), interactive DSA visualizations, JWT auth + Redis sessions.',
    image: '/projects/coderax.jpg',
    featured: true,
    features: [
      { icon: '🏟️', text: 'Custom judge engine + problem arena' },
      { icon: '⚔️', text: 'Real-time 1v1 battles with ELO ranking' },
      { icon: '🧠', text: 'AI Revision Mentor (Groq-powered)' },
      { icon: '🎙️', text: 'Voice-driven mock interviews (Gemini)' },
      { icon: '📐', text: 'Interactive DSA visualizer' },
      { icon: '🔐', text: 'JWT auth + Redis sessions' },
    ],
    tech: ['React', 'Node.js', 'MongoDB', 'Redis', 'Socket.io', 'Groq', 'Gemini', 'JWT'],
    live: 'https://coderax-eosin.vercel.app',
    github: 'https://github.com/Ritik-Sharma28/CodeRax',
  },
  {
    id: 2,
    title: 'DocuMind AI',
    tagline: 'Intelligent Document Chat with RAG',
    description:
      'Upload PDFs and chat with your documents using an advanced RAG pipeline with Pinecone vector search, Redis rate-limiting, and fully Dockerized deployment.',
    image: '/projects/documind.jpg',
    features: [
      { icon: '📄', text: 'PDF upload & intelligent chat' },
      { icon: '🔍', text: 'RAG pipeline with Pinecone' },
      { icon: '🛡️', text: 'Redis rate-limiting' },
      { icon: '🐳', text: 'Dockerized deployment' },
      { icon: '💬', text: 'Context-aware AI responses' },
    ],
    tech: ['MERN', 'Redis', 'Pinecone', 'LangChain', 'Docker', 'RAG'],
    live: 'https://documind-ai-pvqg.onrender.com/',
    github: 'https://github.com/Ritik-Sharma28/DocuMind-AI',
  },
  {
    id: 3,
    title: 'Study Mate',
    tagline: 'Smart Study Partner Matching Platform',
    description:
      'Real-time study partner matching via weighted recommendation algorithms. Features live Socket.io chat, relevance-based content feed, and strict Zod schema validation.',
    image: '/projects/studymate.jpg',
    features: [
      { icon: '💬', text: 'Real-time chat via Socket.io' },
      { icon: '🤝', text: 'Weighted recommendation algorithm' },
      { icon: '📰', text: 'Tag overlap + time-decay feed' },
      { icon: '✅', text: 'Zod schema validation' },
    ],
    tech: ['MERN', 'Socket.io', 'Tailwind CSS', 'Zod', 'JWT'],
    live: 'https://studymate-frontend-kq19.onrender.com/',
    github: 'https://github.com/Ritik-Sharma28/Study_Mate',
  },
  {
    id: 4,
    title: 'Codeforces CP Sheet',
    tagline: 'Structured CP Practice Tracker',
    description:
      'Organized competitive programming problem tracker for Codeforces, categorized by topic, difficulty, and rating with 100+ solved problems.',
    image: '/projects/cpsheet.jpg',
    features: [
      { icon: '📊', text: 'Topic + difficulty categorization' },
      { icon: '🎯', text: '100+ solved problems' },
      { icon: '🧩', text: 'Rating-based organization' },
    ],
    tech: ['C++', 'Competitive Programming', 'DSA', 'Algorithms'],
    github: 'https://github.com/Ritik-Sharma28/Codeforces-CP-Sheet',
  },
]

export const techColors = {
  React:      { bg: 'rgba(97,218,251,0.1)',  text: '#61DAFB', border: 'rgba(97,218,251,0.3)' },
  'Node.js':  { bg: 'rgba(51,153,51,0.1)',   text: '#339933', border: 'rgba(51,153,51,0.3)' },
  MongoDB:    { bg: 'rgba(71,162,72,0.1)',    text: '#47A248', border: 'rgba(71,162,72,0.3)' },
  Redis:      { bg: 'rgba(220,56,45,0.1)',    text: '#DC382D', border: 'rgba(220,56,45,0.3)' },
  Docker:     { bg: 'rgba(36,150,237,0.1)',   text: '#2496ED', border: 'rgba(36,150,237,0.3)' },
  'Socket.io':{ bg: 'rgba(100,100,100,0.1)',  text: '#ffffff', border: 'rgba(100,100,100,0.3)' },
  Groq:       { bg: 'rgba(245,80,54,0.1)',    text: '#F55036', border: 'rgba(245,80,54,0.3)' },
  Gemini:     { bg: 'rgba(142,117,178,0.1)',  text: '#8E75B2', border: 'rgba(142,117,178,0.3)' },
  JWT:        { bg: 'rgba(251,166,3,0.1)',     text: '#FBA603', border: 'rgba(251,166,3,0.3)' },
  MERN:       { bg: 'rgba(34,211,238,0.1)',   text: '#22d3ee', border: 'rgba(34,211,238,0.3)' },
  Pinecone:   { bg: 'rgba(100,100,100,0.1)',  text: '#ffffff', border: 'rgba(100,100,100,0.3)' },
  LangChain:  { bg: 'rgba(28,60,60,0.1)',     text: '#1C3C3C', border: 'rgba(28,60,60,0.3)' },
  RAG:        { bg: 'rgba(139,92,246,0.1)',    text: '#8b5cf6', border: 'rgba(139,92,246,0.3)' },
  'Tailwind CSS': { bg: 'rgba(6,182,212,0.1)', text: '#06B6D4', border: 'rgba(6,182,212,0.3)' },
  Zod:        { bg: 'rgba(59,130,246,0.1)',    text: '#3B82F6', border: 'rgba(59,130,246,0.3)' },
  'C++':      { bg: 'rgba(0,89,156,0.1)',      text: '#00599C', border: 'rgba(0,89,156,0.3)' },
  'Competitive Programming': { bg: 'rgba(245,158,11,0.1)', text: '#F59E0B', border: 'rgba(245,158,11,0.3)' },
  DSA:        { bg: 'rgba(16,185,129,0.1)',    text: '#10b981', border: 'rgba(16,185,129,0.3)' },
  Algorithms: { bg: 'rgba(168,85,247,0.1)',    text: '#A855F7', border: 'rgba(168,85,247,0.3)' },
  default:    { bg: 'rgba(34,211,238,0.08)',   text: '#22d3ee', border: 'rgba(34,211,238,0.2)' },
}
